# Numpy and Pandas 

In [58]:
import numpy as np
import pandas as pd

###  1.	Create a 2D array and print the dim and shape

In [3]:
array1 = np.array([[1,2,3],[4,5,6]])
print("Array Dim:",array1.ndim)
print("Array Shape:",array1.shape)


Array Dim: 2
Array Shape: (2, 3)


### 2.	Create an array of 20 numbers using arange function and slice the values between 10 to 15

In [10]:
array2 = np.arange(20)
slice_array2 = array2[10:15]
slice_array2


array([10, 11, 12, 13, 14])

###  3.	Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using 


In [ ]:
a.	Addition
b.	Subtraction
c.	Multiplication
d.	Division


In [51]:
#Create random 7x5 integer arrays
array1 = np.random.randint(0,5, size=(7, 5))
array2 = np.random.randint(6,10, size=(7, 5))

#Broadcasting operations
sum_array = array1 + array2
sub_array = array2 - array1
multi_array = array1 * array2
div_array = array1 / array2

#Output
print("a. Addition:\n", sum_array)
print("b. Subtraction:\n",sub_array)
print("c. Multiplication:\n",multi_array)
print("d. Division:\n",sum_array)

a. Addition:
 [[ 9 11  9 12  8]
 [ 8 10 11  9  6]
 [10  8 10  8 13]
 [10  9 11 12 11]
 [ 9  7  9  9 13]
 [11  8 11  9  9]
 [10  9  9 10 12]]
b. Subtraction:
 [[7 5 3 6 4]
 [4 8 3 5 6]
 [6 8 8 6 5]
 [6 7 3 4 3]
 [5 5 7 9 5]
 [5 4 5 5 7]
 [4 7 7 4 4]]
c. Multiplication:
 [[ 8 24 18 27 12]
 [12  9 28 14  0]
 [16  0  9  7 36]
 [16  8 28 32 28]
 [14  6  8  0 36]
 [24 12 24 14  8]
 [21  8  8 21 32]]
d. Division:
 [[ 9 11  9 12  8]
 [ 8 10 11  9  6]
 [10  8 10  8 13]
 [10  9 11 12 11]
 [ 9  7  9  9 13]
 [11  8 11  9  9]
 [10  9  9 10 12]]


###  4.	Create 2 incompatible arrays for broadcast and print out the error

In [41]:
array3 = np.random.randint(0,5, size=(5, 7))
array4 = np.random.randint(6,10, size=(7, 5))
array3*array4

ValueError: operands could not be broadcast together with shapes (5,7) (7,5) 

### 5.	Create two arrays of any dimension and perform vstack and hstack

In [57]:
print("vstack: \n",np.vstack((array1,array2)))
print("hstack: \n",np.hstack((array1,array2)))

vstack: 
 [[1 3 3 3 2]
 [2 1 4 2 0]
 [2 0 1 1 4]
 [2 1 4 4 4]
 [2 1 1 0 4]
 [3 2 3 2 1]
 [3 1 1 3 4]
 [8 8 6 9 6]
 [6 9 7 7 6]
 [8 8 9 7 9]
 [8 8 7 8 7]
 [7 6 8 9 9]
 [8 6 8 7 8]
 [7 8 8 7 8]]
hstack: 
 [[1 3 3 3 2 8 8 6 9 6]
 [2 1 4 2 0 6 9 7 7 6]
 [2 0 1 1 4 8 8 9 7 9]
 [2 1 4 4 4 8 8 7 8 7]
 [2 1 1 0 4 7 6 8 9 9]
 [3 2 3 2 1 8 6 8 7 8]
 [3 1 1 3 4 7 8 8 7 8]]


###  6.	Append two arrays using axis = 0 and axis = 1

In [79]:
array1 = np.random.randint(0,5, size=(3, 3))
array2 = np.random.randint(5,10, size=(3, 3))

In [80]:
np.append(array1, array2, axis = 0)

array([[3, 2, 4],
       [0, 1, 0],
       [3, 4, 2],
       [9, 8, 6],
       [8, 8, 9],
       [5, 5, 5]])

In [81]:
np.append(array1, array2, axis = 1)

array([[3, 2, 4, 9, 8, 6],
       [0, 1, 0, 8, 8, 9],
       [3, 4, 2, 5, 5, 5]])

### 7.	Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

In [89]:
list1 = [[1,'Chandler',5.9,'Bing'],
         [2,'Ross',6.2,'Geller'],
         [3,'Monica',5.8,'Geller'],
         [4,'Joey',6.0,'Tribiani'],
         [5,'Phoebe',6.0,'Buffay'],
         [6,'Rachel',5.7,'Green'],
         [7,'Emma',2.5,'Geller'],
         [8,'Ben',4.5,'Geller']]

df1 = pd.DataFrame (list1, columns= ('S.no',"First Name",'Height','Second Name'))
df1

S.no First Name  Height Second Name
0     1   Chandler     5.9        Bing
1     2       Ross     6.2      Geller
2     3     Monica     5.8      Geller
3     4       Joey     6.0    Tribiani
4     5     Phoebe     6.0      Buffay
5     6     Rachel     5.7       Green
6     7       Emma     2.5      Geller
7     8        Ben     4.5      Geller

### 8.	Create a dataframe of 4 X 8 dimension using a dictionary

In [97]:
dict1 = {'S.No':[1,2,3,4],
        'Avengers':['Hulk','Spiderman','Ironman','Thor'],
        'Name':['Banner','Parker','Stark','Odinson'],
        'Occupation':['Doctor','Photographer','Industrialist','King/God'],
        'Height':[5.9,6.1,5.11,6.4],
        'Movies':[6,3,5,7],
        'Weapons':['Smash','Web','Suit','Hammer'],
        'World':['Marvel','Sony','Marvel','Marvel']}

df_avengers = pd.DataFrame (dict1)
df_avengers

S.No   Avengers     Name     Occupation  Height  Movies Weapons   World
0     1       Hulk   Banner         Doctor    5.90       6   Smash  Marvel
1     2  Spiderman   Parker   Photographer    6.10       3     Web    Sony
2     3    Ironman    Stark  Industrialist    5.11       5    Suit  Marvel
3     4       Thor  Odinson       King/God    6.40       7  Hammer  Marvel

### 9.	Use loc and iloc to subset the data for the above dataframe

In [105]:
df_avengers.loc[0:3,['Avengers','Name']]

Avengers     Name
0       Hulk   Banner
1  Spiderman   Parker
2    Ironman    Stark
3       Thor  Odinson

In [110]:
df_avengers.iloc[2:4, 1:4]

Avengers     Name     Occupation
2  Ironman    Stark  Industrialist
3     Thor  Odinson       King/God

### 10.	How to check the total number of not null values in a column?

In [115]:
df_avengers['Name'].notnull().sum()

4

In [116]:
df_avengers['Name'].notnull().count()

4

### 11.	Create a dataframe with missing values and fill them all with 100

In [142]:
df1 = pd.DataFrame(np.random.randint(0,5, size=(5, 3)), index = ['id_0','id_1','id_3','id_5','id_7'],columns= ['Col_1', 'Col_2', 'Col_3'])
Missing_df = df1.reindex(['id_0','id_1','id_2','id_3','id_4','id_5','id_6','id_7'])

In [144]:
Missing_df.fillna(100)

Col_1  Col_2  Col_3
id_0    1.0    2.0    1.0
id_1    4.0    3.0    3.0
id_2  100.0  100.0  100.0
id_3    0.0    4.0    4.0
id_4  100.0  100.0  100.0
id_5    3.0    2.0    3.0
id_6  100.0  100.0  100.0
id_7    1.0    3.0    1.0

### 12.	Create a dataframe with missing values and drop the null records

In [145]:
df1 = pd.DataFrame(np.random.randint(0,5, size=(5, 3)), index = ['id_0','id_1','id_3','id_5','id_7'],columns= ['Col_1', 'Col_2', 'Col_3'])
Missing_df = df1.reindex(['id_0','id_1','id_2','id_3','id_4','id_5','id_6','id_7'])

In [146]:
Missing_df.dropna()

Col_1  Col_2  Col_3
id_0    4.0    1.0    2.0
id_1    0.0    0.0    0.0
id_3    1.0    4.0    1.0
id_5    0.0    1.0    1.0
id_7    0.0    2.0    4.0

### 13.	Perform following aggregation task on below table


In [147]:
Table = pd.DataFrame({ 'Age' :  [25,30,45,35,33,35,25,52,21,24,48,22,27,28,21,51,23] ,
 'Hair Color' :  [ 'Black' , 'Black' , 'Red' , 'Blond' , 'Brown' , 'Brown' , 'Black' , 'Brown' , 'Blond' , 'Blond' , 'Black' , 'Black' , 'Brown' , 'Black' , 'Blond' , 'Black' , 'Brown' ] ,
 'U.S. Region' :  [ 'Southwest' , 'Northwest' , 'Northeast' , 'Southwest' , 'Southwest' , 'Northeast' , 'Southwest' , 'Southeast' , 'Southwest' , 'Northeast' , 'Southwest' , 'Southwest' , 'Northeast' , 'Southeast' , 'Southeast' , 'Northwest' , 'Southeast' ] ,
 'Validation' :  [1,1,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1] 
})

In [148]:
Table

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    35      Brown   Northeast           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    24      Blond   Northeast           0
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1

#### a.	Get the average age group by Region

In [152]:
Table.groupby(['U.S. Region'])['Age'].agg(np.mean)

U.S. Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

#### b.	Get the sum of Age and Validation group by Hair color and then reset the index

In [158]:
Table.groupby(['Hair Color'])['Age','Validation'].sum().reset_index()

C:\Users\subramanian2\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.


Hair Color  Age  Validation
0      Black  229           4
1      Blond  101           2
2      Brown  170           1
3        Red   45           1

#### c.	Get the mean and the median of Age group by Region

In [160]:
Table.groupby(['U.S. Region'])['Age'].agg([np.mean, np.median])

mean  median
U.S. Region                   
Northeast    32.750000    31.0
Northwest    40.500000    40.5
Southeast    31.000000    25.5
Southwest    29.857143    25.0

### 14.	Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

In [165]:
Table_left = Table.head(9)
Table_right = Table.tail(8)

#### Inner Join

In [176]:
pd.merge(Table_left, Table_right, on=['U.S. Region'])

Age_x Hair Color_x U.S. Region  Validation_x  Age_y Hair Color_y  \
0      25        Black   Southwest             1     48        Black   
1      25        Black   Southwest             1     22        Black   
2      35        Blond   Southwest             0     48        Black   
3      35        Blond   Southwest             0     22        Black   
4      33        Brown   Southwest             0     48        Black   
5      33        Brown   Southwest             0     22        Black   
6      25        Black   Southwest             0     48        Black   
7      25        Black   Southwest             0     22        Black   
8      21        Blond   Southwest             1     48        Black   
9      21        Blond   Southwest             1     22        Black   
10     30        Black   Northwest             1     51        Black   
11     45          Red   Northeast             1     24        Blond   
12     45          Red   Northeast             1     27        Brown   
13     35        Brown   Northeast             0     24        Blond   
14     35        Brown   Northeast             0     27        Brown   
15     52        Brown   Southeast             0     28        Black   
16     52        Brown   Southeast             0     21        Blond   
17     52        Brown   Southeast             0     23        Brown   

    Validation_y  
0              1  
1              0  
2              1  
3              0  
4              1  
5              0  
6              1  
7              0  
8              1  
9              0  
10             0  
11             0  
12             0  
13             0  
14             0  
15             1  
16             1  
17             1

#### Left Join

In [178]:
Table_left.merge(Table_right, on=['U.S. Region'], how = 'left')

Age_x Hair Color_x U.S. Region  Validation_x  Age_y Hair Color_y  \
0      25        Black   Southwest             1     48        Black   
1      25        Black   Southwest             1     22        Black   
2      30        Black   Northwest             1     51        Black   
3      45          Red   Northeast             1     24        Blond   
4      45          Red   Northeast             1     27        Brown   
5      35        Blond   Southwest             0     48        Black   
6      35        Blond   Southwest             0     22        Black   
7      33        Brown   Southwest             0     48        Black   
8      33        Brown   Southwest             0     22        Black   
9      35        Brown   Northeast             0     24        Blond   
10     35        Brown   Northeast             0     27        Brown   
11     25        Black   Southwest             0     48        Black   
12     25        Black   Southwest             0     22        Black   
13     52        Brown   Southeast             0     28        Black   
14     52        Brown   Southeast             0     21        Blond   
15     52        Brown   Southeast             0     23        Brown   
16     21        Blond   Southwest             1     48        Black   
17     21        Blond   Southwest             1     22        Black   

    Validation_y  
0              1  
1              0  
2              0  
3              0  
4              0  
5              1  
6              0  
7              1  
8              0  
9              0  
10             0  
11             1  
12             0  
13             1  
14             1  
15             1  
16             1  
17             0

#### Right Join

In [177]:
Table_left.merge(Table_right, on=['U.S. Region'], how = 'right')

Age_x Hair Color_x U.S. Region  Validation_x  Age_y Hair Color_y  \
0      25        Black   Southwest             1     48        Black   
1      35        Blond   Southwest             0     48        Black   
2      33        Brown   Southwest             0     48        Black   
3      25        Black   Southwest             0     48        Black   
4      21        Blond   Southwest             1     48        Black   
5      25        Black   Southwest             1     22        Black   
6      35        Blond   Southwest             0     22        Black   
7      33        Brown   Southwest             0     22        Black   
8      25        Black   Southwest             0     22        Black   
9      21        Blond   Southwest             1     22        Black   
10     30        Black   Northwest             1     51        Black   
11     45          Red   Northeast             1     24        Blond   
12     35        Brown   Northeast             0     24        Blond   
13     45          Red   Northeast             1     27        Brown   
14     35        Brown   Northeast             0     27        Brown   
15     52        Brown   Southeast             0     28        Black   
16     52        Brown   Southeast             0     21        Blond   
17     52        Brown   Southeast             0     23        Brown   

    Validation_y  
0              1  
1              1  
2              1  
3              1  
4              1  
5              0  
6              0  
7              0  
8              0  
9              0  
10             0  
11             0  
12             0  
13             0  
14             0  
15             1  
16             1  
17             1

### 15.	Split the below table and perform concat row wise and column wise


In [174]:
Table

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    35      Brown   Northeast           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    24      Blond   Northeast           0
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1

In [179]:
pd.concat([Table_left, Table_right], axis=1)

Age Hair Color U.S. Region  Validation   Age Hair Color U.S. Region  \
0   25.0      Black   Southwest         1.0   NaN        NaN         NaN   
1   30.0      Black   Northwest         1.0   NaN        NaN         NaN   
2   45.0        Red   Northeast         1.0   NaN        NaN         NaN   
3   35.0      Blond   Southwest         0.0   NaN        NaN         NaN   
4   33.0      Brown   Southwest         0.0   NaN        NaN         NaN   
5   35.0      Brown   Northeast         0.0   NaN        NaN         NaN   
6   25.0      Black   Southwest         0.0   NaN        NaN         NaN   
7   52.0      Brown   Southeast         0.0   NaN        NaN         NaN   
8   21.0      Blond   Southwest         1.0   NaN        NaN         NaN   
9    NaN        NaN         NaN         NaN  24.0      Blond   Northeast   
10   NaN        NaN         NaN         NaN  48.0      Black   Southwest   
11   NaN        NaN         NaN         NaN  22.0      Black   Southwest   
12   NaN        NaN         NaN         NaN  27.0      Brown   Northeast   
13   NaN        NaN         NaN         NaN  28.0      Black   Southeast   
14   NaN        NaN         NaN         NaN  21.0      Blond   Southeast   
15   NaN        NaN         NaN         NaN  51.0      Black   Northwest   
16   NaN        NaN         NaN         NaN  23.0      Brown   Southeast   

    Validation  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          NaN  
9          0.0  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0

In [180]:
pd.concat([Table_left, Table_right], axis=0)

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    35      Brown   Northeast           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    24      Blond   Northeast           0
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1