### Questions

1.	Create a program that asks the user to enter their name and their age. Print out a message that tells them the year that they will turn 100 years old
2.	What is pandas groupby? Demonstrate with your own example
3.	How to create a dataframe from list?
4.	What are the ways to combine the dataframe in pandas. Give an example for each
5.	What is the difference between list and tuples in Python?
6.	Find out the mean, median and standard deviation of this numpy array -> np.array([1,5,3,100,4,48])
7.	How will you remove duplicate elements from a list?
8.	What is a map() function in Python? Give an example
9.	What is pass in Python?
10.	What is vstack() in numpy? Give an example


In [5]:
#Create a program that asks the user to enter their name and their age. 
#Print out a message that tells them the year that they will turn 100 years old
from datetime import date
  
age = int(input("Enter your age:"))
name = input ("Enter your Name:")
birth_year = (date.today().year) - age
print("You will turn 100 years on:", birth_year+100)

Enter your age:33
Enter your Name:Suresh
You will turn 100 years on: 2089


In [8]:
#What is pandas groupby? Demonstrate with your own example

# Groupby is a function to split the data into unique categories by making an aggregation on the output dataset

import pandas as pd
import numpy as np
Table = pd.DataFrame({ 'Age' :  [25,30,45,35,33,35,25,52,21,24,48,22,27,28,21,51,23] ,
 'Hair Color' :  [ 'Black' , 'Black' , 'Red' , 'Blond' , 'Brown' , 'Brown' , 'Black' , 'Brown' , 'Blond' , 'Blond' , 'Black' , 'Black' , 'Brown' , 'Black' , 'Blond' , 'Black' , 'Brown' ] ,
 'U.S. Region' :  [ 'Southwest' , 'Northwest' , 'Northeast' , 'Southwest' , 'Southwest' , 'Northeast' , 'Southwest' , 'Southeast' , 'Southwest' , 'Northeast' , 'Southwest' , 'Southwest' , 'Northeast' , 'Southeast' , 'Southeast' , 'Northwest' , 'Southeast' ] ,
 'Validation' :  [1,1,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1] 
})
Table.groupby(['U.S. Region'])['Age'].agg(np.mean)

U.S. Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

In [12]:
# How to create a dataframe from list?
# Create a list of list with values; declare a dataframe object and include that list along with column names (optional)

list1 = [[1,'Chandler',5.9,'Bing'],
         [2,'Ross',6.2,'Geller'],
         [3,'Monica',5.8,'Geller'],
         [4,'Joey',6.0,'Tribiani'],
         [5,'Phoebe',6.0,'Buffay'],
         [6,'Rachel',5.7,'Green'],
         [7,'Emma',2.5,'Geller'],
         [8,'Ben',4.5,'Geller']]

df = pd.DataFrame (list1, columns= ('S.no',"First Name",'Height','Second Name'))
df

S.no First Name  Height Second Name
0     1   Chandler     5.9        Bing
1     2       Ross     6.2      Geller
2     3     Monica     5.8      Geller
3     4       Joey     6.0    Tribiani
4     5     Phoebe     6.0      Buffay
5     6     Rachel     5.7       Green
6     7       Emma     2.5      Geller
7     8        Ben     4.5      Geller

In [19]:
# What are the ways to combine the dataframe in pandas. Give an example for each

df1 = df.head(3)
df2 = df.tail(3)

#Concat
pd.concat([df1,df2])

#Join
pd.concat([df1,df2], axis = 1, join = 'outer')

#append
df1.append(df2)

#merge

df1.merge(df2)

Empty DataFrame
Columns: [S.no, First Name, Height, Second Name]
Index: []

In [22]:
#What is the difference between list and tuples in Python?

#Lists are mutable whereas tuples are immutable. The syntax for list is [] where as for tuple it is (). 
#The list follows an ordered operation and can contain multiple datatypes. Both follows similar indexing method (0 to n-1)

list1 = ['a', 12, 5.6]
tuple1 = (1,2,3)

In [25]:
#Find out the mean, median and standard deviation of this numpy array -> np.array([1,5,3,100,4,48])
array1 = np.array([1,5,3,100,4,48])
print(np.mean(array1,axis=0))
print(np.median(array1,axis=0))
print(np.std(array1,axis=0))

26.833333333333332
4.5
36.59424666377065


In [26]:
# How will you remove duplicate elements from a list?
#enumerate is one of an option

list2 = [1,2,3,4,5,5,5,5,5]
res = [i for n, i in enumerate(list2) if i not in list2[:n]]
res

[1, 2, 3, 4, 5]

In [28]:
#What is a map() function in Python? Give an example

#Map applies the predefined function for all the items in any datatype variable

new_list = map(lambda x:x*2, list2)
list(new_list)

[2, 4, 6, 8, 10, 10, 10, 10, 10]

In [40]:
#What is pass in Python?

#The compiler will ignore the code execution after this statement and will skip out of the implementation but will retain the executed output for future
# Ex - 

def fun1(x):
    if x == 2:
        pass
    else:
        print ("Not 2")
    
fun1(2)    

In [39]:
# What is vstack() in numpy? Give an example

#Vstack or vertical stack is a function to vertically stack multiple arrays to form a single array

#Eg- 

array1 = np.random.randint(0,5, size=(2, 3))
array2 = np.random.randint(6,10, size=(2, 3))
print("vstack: \n",np.vstack((array1,array2)))

vstack: 
 [[3 1 1]
 [1 0 3]
 [8 6 8]
 [9 9 8]]
